### ISSUE TITLE
You're missing status code 418

### ISSUE THREAD

**Issue by NicolasCARPi** [alexanderpas/php-http-enum#1]
It's a very important one ;)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418

**Comment by alexanderpas** [comment]
The Status Code and corresponding Reason Phrase defined in the [Hyper Text Coffee Pot Control Protocol](https://en.wikipedia.org/wiki/HTCPCP) ([RFC 2324](https://www.iana.org/go/rfc2324)) is not supported as it isn't properly registed with IANA.

It will be included as soon as it's added to the list of  [IANA registered HTTP Status codes](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml)
